todo/todop/todoapp/urls.py
from django.urls import path,include
from .  import views
app_name='todo'

urlpatterns = [
    path('',views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('update/<int:task_id>/', views.update, name='update'),
    path('cvhome/', views.Taskview.as_view(), name='cvhome'),
    path('cvdetail/<int:pk>/', views.TaskDetailview.as_view(),name='cvdetail'),
    path('cvupdate/<int:pk>/', views.TaskUpdate.as_view(), name='cvupdate'),
    path('cvdelete/<int:pk>/', views.TaskDelete.as_view(), name='cvdelete'),

]

todo/todop/todop/urls.py
from django.contrib import admin
from django.urls import path,include
from todop import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,
                                document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,
                                document_root=settings.MEDIA_ROOT)

todo/todop/todoapp/models.py
from django.db import models

# Create your models here.



class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField(default=00000)
    date=models.DateField()

    def __str__(self):
             return self.name

todo/todop/todoapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from todoapp.models import Task
from . form import TaskForm
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views here.
def index(request):
    return render(request, "index.html")

class Taskview(ListView):
    model = Task
    template_name = 'add.html'
    context_object_name = 'task'

class TaskDetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class TaskUpdate(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields =('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todo:cvdetail',kwargs={'pk':self.object.id})

class TaskDelete(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todo:cvhome')
def add(request):
    obj = Task.objects.all()
    if request.method=='POST':
        tname=request.POST.get('tname','')
        prio=request.POST.get('prio','')
        date=request.POST.get('date','')
        task=Task(name=tname, priority=prio,date=date)
        task.save()
        # return redirect('/')
    return render(request,"add.html",{'task': obj})
def delete(request,task_id):
    task = Task.objects.get(id=task_id)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html',{'task': task})

def update(request,task_id):
    task=Task.objects.get(id=task_id)
    form=TaskForm(request.POST or None,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html',{'form':form,'task':task})

todo/todop/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
	<div class="row">
			<div class="col-md-12">
				<div class="banner">
					<div class="banner-text">
				<h1>TODO</h1>

					</div>
			</div>

			</div>
	</div>

</div>
<div class="row">
	<div class="col-md-6" style="padding-left: 50px;">
		<div class="shadow card" >
				<div class="card-body">
<form action="" method="POST">
								{% csrf_token %}
								<label class="form-label" for="tname">Task name:</label><br>
								<input class="form-control" type="text" id="tname" name="tname" ><br>

								<label class="form-label" for="prio">Enter Task priority:</label><br>
								<input class="form-control" type="text" id="prio" name="prio" ><br>

								<label class="form-label" for="date">Enter Task Date:</label><br>
								<input class="form-control" type="date" id="date" name="date" ><br>

								<div ><input  class="btn btn-primary mb-3" type="submit" value="Add Task"></div>

							</form>
					</div>
			</div>

		</div>

		<div class="col-md-6" style="padding-right: 50px;">
			<h4>Task to complete</h4>
			        {% for i in task %}

			<div class="shadow card" >
				<div class="card-body">
					<h5 class="card-title">{{i.name}}</h5>
					<P><b>{{i.priority}}</b></P>
					<P><b>{{i.date}}</b></P>

					<a href="{% url 'todo:delete' i.id %}" class="btn btn-danger">Done</a>
					<a href="{% url 'todo:update' i.id %}" class="btn btn-success">Update</a> <br>

				</div>
			</div>
			<br>

			{% endfor %}

		</div>

</div>


{% endblock %}

todo/todop/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#" style="padding-left: 20px;">ToDo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'todo:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:add' %}">Add Task</a>
      </li>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

todo/todop/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div style="display: block; margin-left: auto ;margin-right: auto; width: 55%;">
  <form method="POST">
    {% csrf_token %}
      <h3>Did you Finished this task?</h3>
<div class="col-md-6" style="padding-right: 50px;">

			<div class="shadow card" >
				<div class="card-body">
					<h5 class="card-title">{{task.name}}</h5>
					<P><b>{{task.priority}}</b></P>
					<P><b>{{task.date}}</b></P>

				</div>

			</div>
	 <br>
<input style="color:white" class="btn btn-danger" type="submit" value="Done">

		</div>   <br><br>
</form>
</div>
{% endblock %}

todo/todop/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
	<div class="row">
			<div class="col-md-12">
				<div class="banner">
					<div class="banner-text">
				<h1>TODO</h1>

					</div>
			</div>

			</div>
	</div>

</div>
<div class="row">

		<div class="col-md-6" style="padding-right: 50px;">
			<h4>Task to complete</h4>
			<div class="shadow card" >
				<div class="card-body">
					<h5 class="card-title">{{task.name}}</h5>
					<P><b>{{task.priority}}</b></P>
					<P><b>{{task.date}}</b></P>

					<a href="{% url 'todo:delete' task.pk %}" class="btn btn-danger">Done</a>
					<a href="{% url 'todo:update' task.pk %}" class="btn btn-success">Update</a> <br>

				</div>
			</div>
			<br>


		</div>

</div>


{% endblock %}

todo/todop/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div style="display: block;margin-left: auto; margin-right: auto; width: 25%;">
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  								<div ><input style="color:black" class="button about_button" type="submit" value="Update"></div>

</form>
</div>
{% endblock %}

todo/todop/templates/index.html
{% extends 'base.html' %}
{% block body %}

<br>
    <a href="{% url 'todo:add' %}" class="btn btn-primary">Add Task</a>

{% endblock %}

todo/todop/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
	<div class="row">
			<div class="col-md-12">
				<div class="banner">
					<div class="banner-text">
				<h1>TODO</h1>

					</div>
			</div>

			</div>
	</div>

</div>
<div class="row">
	<div class="col-md-6" style="padding-left: 50px;">
		<div class="shadow card" >
				<div class="card-body">
					<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  								<div ><input style="color:black" class="button about_button" type="submit" value="Update"></div>

</form>
					</div>
			</div>

		</div>

    </div>


{% endblock %}